executor-machine: &executor-machine 'ubuntu-2004:2022.04.1'

jobs:
    test_back_category_ee:
        machine:
            image: *executor-machine
            docker_layer_caching: true
        parameters:
            notify:
                type: boolean
                default: false
        steps:
            -   attach_workspace:
                    at: ~/
            - install_yq_v3
            - set_docker_gcp_mirror
            - fix_files_permissions
            - load_docker_image_php
            -   run:
                    name: Lint back
                    command: PIM_CONTEXT=category APP_ENV=test make category-lint-back
            -   run:
                    name: Coupling back
                    command: PIM_CONTEXT=category make category-coupling-back
            -   run:
                    name: Start containers
                    command: |
                        APP_ENV=test C='fpm mysql elasticsearch object-storage pubsub-emulator' make up
                        docker/wait_docker_up.sh
            -   run:
                    name: Install database
                    command: APP_ENV=test make database
            -   run:
                    name: Unit back
                    command: PIM_CONTEXT=category make category-unit-back
            -   run:
                    name: Integration back
                    command: PIM_CONTEXT=category APP_ENV=test make category-integration-back
            -   run:
                    name: End to End back
                    command: PIM_CONTEXT=category APP_ENV=test make category-end-to-end-back
            -   when:
                    condition: << pipeline.parameters.run-database-tests >>
                    steps:
                        -   run:
                                name: Database schema reference
                                command: PIM_CONTEXT=test APP_ENV=test make test-database-structure
            -   when:
                    condition: << parameters.notify >>
                    steps:
                        -   slack-app/notify:
                                channel: 'monitoring-octopus'
                                event: fail
                                template: basic_fail_1
