jobs:
    test_back_category_ce:
        machine:
            image: 'ubuntu-2004:2022.04.1'
            docker_layer_caching: true
        steps:
            -   attach_workspace:
                    at: ~/
            -   load_docker_image_php
            -   fix_files_permissions
            -   run:
                    name: Coupling back
                    command: PIM_CONTEXT=category make category-coupling-back
            -   run:
                    name: Lint back
                    command: PIM_CONTEXT=category make category-lint-back
            -   start_test_containers
            -   run:
                    name: Unit back
                    command: PIM_CONTEXT=category make category-unit-back
            -   run:
                    name: Integration back
                    command: PIM_CONTEXT=category APP_ENV=test make category-integration-back
            -   run:
                    name: End to End back
                    command: PIM_CONTEXT=category APP_ENV=test make category-end-to-end-back
            -   when:
                    condition: << pipeline.parameters.run-database-tests >>
                    steps:
                        -   run:
                                name: Lint migrations
                                command: make migration-lint-back migration-coupling-back
                        -   run:
                                name: Migrations tests
                                command: CI=false make migration-back
            -   store_test_results:
                    path: var/tests/phpunit
