pim_enrich_category_rest_list_selected_children:
    path: /rest/{identifier}/selected-children
    defaults: { _controller: pim_enrich.controller.rest.category:listSelectedChildrenAction }
    methods: [POST]

pim_enrich_category_rest_list:
    path: /rest
    defaults: { _controller: pim_enrich.controller.rest.category:listAction }
    methods: [GET]

pim_enrich_category_rest_get:
    path: /rest/{identifier}
    defaults: { _controller: pim_enrich.controller.rest.category:getAction }
    methods: [GET]


pim_enrich_category_rest_template_get:
    path: /template/{identifier}
    defaults: { _controller: Akeneo\Category\Infrastructure\Controller\InternalApi\GetTemplate }
    methods: [GET]

pim_enrich_category_rest_template_edit:
    path: /template
    defaults: { _controller: Akeneo\Category\Infrastructure\Controller\InternalApi\EditTemplate }
    methods: [POST]
