pim_category_template_rest_get_by_template_uuid:
    path: /rest/{templateUuid}
    defaults:
        _controller: Akeneo\Category\Infrastructure\Controller\InternalApi\GetTemplateController:byTemplateUuid
        _feature: enriched_category
    methods: [GET]

pim_category_template_rest_get_by_template_uuid_in_memory:
    path: /rest/in-memory/{templateUuid}
    defaults:
        _controller: Akeneo\Category\Infrastructure\Controller\InternalApi\GetTemplateController:byTemplateUuidInMemory
        _feature: enriched_category
    methods: [GET]

pim_category_template_rest_create:
    path: /rest/{categoryTreeId}
    defaults:
        _controller: Akeneo\Category\Infrastructure\Controller\InternalApi\CreateTemplateController
        _feature: enriched_category
    methods: [POST]

pim_category_template_attributes_rest_delete:
    path: /rest/{templateUuid}/attributes
    defaults:
        _controller: Akeneo\Category\Infrastructure\Controller\InternalApi\DeleteTemplateAttributesController
        _feature: enriched_category
    methods: [DELETE]
