parameters:
    oro_config.global.class:                                                     Akeneo\Platform\Bundle\ConfigBundle\Config\ConfigManager
    oro_config.user.class:                                                       Akeneo\Platform\Bundle\ConfigBundle\Config\UserConfigManager
    oro_config.twig_extension.class:                                             Akeneo\Platform\Bundle\ConfigBundle\Twig\ConfigExtension
    oro_config.provider.system_configuration.form_provider.class:                Akeneo\Platform\Bundle\ConfigBundle\Provider\SystemConfigurationFormProvider

services:
    oro_config.user:
        class:                        '%oro_config.user.class%'
        arguments:                    ["@doctrine.orm.entity_manager"]
        calls:
             - [setSecurity, ["@security.token_storage"]]
        tags:
            -  { name: oro_config.manager }

    oro_config.global:
        class:                        '%oro_config.global.class%'
        arguments:                    ["@doctrine.orm.entity_manager"]
        tags:
            -  { name: oro_config.manager }

    oro_config.twig.config_extension:
        class:                        '%oro_config.twig_extension.class%'
        arguments:                    ["@oro_config.global"]
        tags:
            - { name: twig.extension }
