services:
    Akeneo\Connectivity\Connection\Application\Settings\Validation\Connection\CodeMustBeUniqueValidator:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Settings\Persistence\DbalConnectionRepository'
        tags:
            - { name: validator.constraint_validator, alias: connection_code_must_be_unique }

    Akeneo\Connectivity\Connection\Application\Settings\Validation\Connection\ImageMustExistValidator:
        arguments:
            - '@akeneo_connectivity.connection.service.file_info.does_image_exist'
        tags:
            - { name: validator.constraint_validator, alias: connection_image_must_exist }

    Akeneo\Connectivity\Connection\Application\Settings\Validation\Connection\IsConnectionsNumberLimitReachedValidator:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Settings\Persistence\IsConnectionsNumberLimitReachedQuery'
        tags:
            - { name: validator.constraint_validator }
