services:
    Akeneo\Pim\Enrichment\Product\Application\Applier\UserIntentApplierRegistry:
        arguments:
            - !tagged_iterator 'pim.enrichment.product.user_intent_applier'

    Akeneo\Pim\Enrichment\Product\Application\Applier\SetEnabledApplier:
        tags:
            - { name: 'pim.enrichment.product.user_intent_applier' }
