services:
    Akeneo\Connectivity\Connection\Infrastructure\Cli\CreateConnectionCommand:
        class: Akeneo\Connectivity\Connection\Infrastructure\Cli\CreateConnectionCommand
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Settings\Command\CreateConnectionHandler'
        tags:
            - { name: 'console.command' }
