services:
    Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Connection\ListConnectionsAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Settings\Query\FetchConnectionsHandler'

    Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Connection\CreateConnectionAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Settings\Command\CreateConnectionHandler'
            - '@oro_security.security_facade'

    Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Connection\GetConnectionAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Settings\Query\FindAConnectionHandler'
            - '@oro_security.security_facade'

    Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Connection\UpdateConnectionAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Settings\Command\UpdateConnectionHandler'
            - '@oro_security.security_facade'

    Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Connection\DeleteConnectionAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Settings\Command\DeleteConnectionHandler'
            - '@oro_security.security_facade'

    Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Connection\RegenerateSecretAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Settings\Command\RegenerateConnectionSecretHandler'
            - '@oro_security.security_facade'

    Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Connection\RegeneratePasswordAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Settings\Command\RegenerateConnectionPasswordHandler'
            - '@oro_security.security_facade'
