parameters:
    akeneo_pim_marketplace_url: 'https://marketplace.akeneo.com'
    akeneo_pim_marketplace_api_pagination_size: 100

services:
    akeneo_connectivity.connection.marketplace.url_generator:
        class: Akeneo\Connectivity\Connection\Application\Marketplace\MarketplaceUrlGenerator
        arguments:
            - '%akeneo_pim_marketplace_url%'
            - '@pim_catalog.version_provider'
            - '%env(AKENEO_PIM_URL)%'
            - '@akeneo_connectivity.connection.marketplace.query.get_user_profile'

    akeneo_connectivity.connection.marketplace.analytics_generator:
        class: Akeneo\Connectivity\Connection\Application\Marketplace\MarketplaceAnalyticsGenerator
        arguments:
            - '@akeneo_connectivity.connection.marketplace.query.get_user_profile'
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_aliases'
            - '@pim_framework.service.pim_url'
            -
    akeneo_connectivity.connection.marketplace.app_url_generator:
        class: Akeneo\Connectivity\Connection\Application\Marketplace\AppUrlGenerator
        arguments:
            - '@pim_framework.service.pim_url'

    akeneo_connectivity.connection.marketplace.query.get_user_profile:
        class: Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\DbalGetUserProfileQuery
        arguments:
            - '@database_connection'

    akeneo_connectivity.connection.marketplace.guzzle_client:
        class: GuzzleHttp\Client
        arguments:
            -
                base_uri: '%akeneo_pim_marketplace_url%'
                headers: {User-Agent: ~}

    akeneo_connectivity.connection.marketplace.web_marketplace_api:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\WebMarketplaceApi
        arguments:
            - '@akeneo_connectivity.connection.marketplace.guzzle_client'
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_aliases'
            - '@logger'
            - '@akeneo_connectivity.connection.marketplace_fake_apps.feature'
        calls:
            - setFixturePath: [ '%connectivity.marketplace_fixtures_directory%' ]

    akeneo_connectivity.connection.marketplace.web_marketplace_aliases:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\WebMarketplaceAliases
        arguments:
            - '@pim_catalog.version_provider'

    akeneo_connectivity.connection.marketplace.get_all_extensions_query:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetAllExtensionsQuery
        arguments:
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_api'
            - '%akeneo_pim_marketplace_api_pagination_size%'
            -
    akeneo_connectivity.connection.marketplace.get_all_apps_query:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetAllAppsQuery
        arguments:
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_api'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\Query\GetAllConnectedAppsPublicIdsQuery'
            - '%akeneo_pim_marketplace_api_pagination_size%'

    akeneo_connectivity.connection.marketplace.get_app_query:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetAppQuery
        arguments:
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_api'
            - '@akeneo_connectivity.connection.app_developer_mode.feature'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetTestAppQuery'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetTestAppQuery:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetTestAppQuery
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetAllTestAppsQuery:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetAllTestAppsQuery
        arguments:
            - '@database_connection'

    # TestApps
    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Controller\InternalApi\CreateTestAppsAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.app_developer_mode.feature'
            - '@validator'
            - '@security.token_storage'
            - '@Akeneo\Connectivity\Connection\Application\Marketplace\TestApps\Command\CreateTestAppCommandHandler'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\GetTestAppSecretQuery'
            - '@oro_security.security_facade'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Controller\InternalApi\DeleteTestAppAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.app_developer_mode.feature'
            - '@oro_security.security_facade'
            - '@Akeneo\Connectivity\Connection\Application\Marketplace\TestApps\Command\DeleteTestAppHandler'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetTestAppQuery'
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\DeleteAppHandler'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\CreateTestAppQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\GetTestAppSecretQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\DeleteTestAppQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Application\Marketplace\TestApps\Command\CreateTestAppCommandHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Service\RandomCodeGenerator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\CreateTestAppQuery'

    Akeneo\Connectivity\Connection\Application\Marketplace\TestApps\Command\DeleteTestAppHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetTestAppQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\DeleteTestAppQuery'
