settings:
    analysis:
        normalizer:
            text_normalizer:
                filter: ['lowercase']

mappings:
    properties:
        id:
            type: 'keyword'
        code:
            type: 'keyword'
            normalizer: 'text_normalizer'
        updated_at:
            type: 'date'

    dynamic_templates:
        -
            category_code_label_search:
                path_match: 'category_code_label_search.*'
                mapping:
                    type: 'keyword'
                    normalizer: 'text_normalizer'
