services:
    Akeneo\Category\Application\Enrichment\CategoryDataCleaner:
        arguments:
            - '@Akeneo\Category\Application\Storage\UpdateCategoryEnrichedValues'
            - '@Akeneo\Category\Application\Query\GetAttribute'
