services:
    Akeneo\Category\Application\Enrichment\CategoryDataCleaner:
        arguments:
            - '@Akeneo\Category\Application\Storage\UpdateCategoryEnrichedValues'
            - '@Akeneo\Category\Application\Enrichment\CategoryImageDataCleaner'

    Akeneo\Category\Application\Enrichment\CategoryImageDataCleaner:
        arguments:
            - '@Akeneo\Category\Infrastructure\FileSystem\Remover\DeleteFilesFromPaths'
            - '@pim_category.infrastructure.registry.preview_generator'

    Akeneo\Category\Application\Query\GetEnrichedValuesPerCategoryCode:
        class: Akeneo\Category\Infrastructure\Storage\Sql\GetEnrichedValuesPerCategoryCodeSql
        arguments:
            - '@database_connection'

    Akeneo\Category\Application\Storage\UpdateCategoryEnrichedValues:
        class: Akeneo\Category\Infrastructure\Storage\Sql\Update\UpdateCategoryEnrichedValuesSql
        arguments:
            - '@database_connection'
