services:
    Akeneo\Category\Application\Enrichment\CategoryAttributeValuesCleaner:
        arguments:
            - '@Akeneo\Category\Application\Storage\UpdateCategoryEnrichedValues'
            - '@Akeneo\Category\Application\Query\GetAttribute'
