services:
    Akeneo\Category\Infrastructure\Cli\CheckCategoryTrees\CheckCategoryTrees:
        arguments:
            - '@database_connection'
        tags:
            - { name: console.command }

    Akeneo\Category\Infrastructure\Cli\RemoveOrphanCategories\RemoveOrphanCategoriesCommand:
        arguments:
            - '@Akeneo\Category\Domain\Query\PurgeOrphanCategories'
        tags:
            - { name: console.command }

    Akeneo\Category\Infrastructure\Cli\PurgeOrphanCategoryImageFilesCommand:
        arguments:
            - '@database_connection'
            - '@akeneo_file_storage.file_storage.filesystem_provider'
            - '@akeneo_file_storage.repository.file_info'
        tags:
            - { name: console.command }
