services:
  Akeneo\Category\API\Query\GetCategory: '@Akeneo\Category\Infrastructure\Storage\Query\OrmGetCategory'

  Akeneo\Category\Infrastructure\Storage\Query\OrmGetCategory:
    arguments:
      - '@pim_catalog.repository.category'
      - '@pim_catalog.repository.cached_locale'
