services:
    pim_catalog.repository.category:
        class: 'Akeneo\Category\Infrastructure\Doctrine\ORM\Repository\CategoryRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - '%pim_catalog.entity.category.class%'
        tags:
            - { name: 'category_repository' }

    pim_api.repository.category:
        class: 'Akeneo\Category\Infrastructure\Doctrine\ORM\Repository\ExternalApi\CategoryRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.category.class%'
            - '@pim_catalog.repository.category'

    pim_enrich.repository.category:
        public: true
        class: 'Akeneo\Category\Infrastructure\Doctrine\ORM\Repository\InternalApi\CategoryRepository'
        arguments:
            - '@pim_user.context.user'
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.category.class%'
