services:
  akeneo.category.indexer:
    class: Akeneo\Category\Infrastructure\Elasticsearch\CategoryIndexer
    arguments:
      - '@akeneo_elasticsearch.client.category'
      - '@pim_catalog.repository.category'
      - '@pim_catalog.normalizer.standard.translation'

  akeneo.category.event_subscriber.on_save.update_index:
    class: Akeneo\Category\Infrastructure\EventSubscriber\OnSave\UpdateIndexSubscriber
    arguments:
      - '@akeneo.category.indexer'
    tags:
      - { name: kernel.event_subscriber }
