services:
  akeneo.category.indexer:
    class: Akeneo\Category\Infrastructure\Elasticsearch\CategoryIndexer
    public: true
    arguments:
      - '@akeneo_elasticsearch.client.category'
      - '@database_connection'
