services:
    Akeneo\Tool\Bundle\MessengerBundle\Command\ProcessMessageCommand:
        arguments:
            - '@akeneo_messenger.message.serializer'
            - '@Akeneo\Tool\Bundle\MessengerBundle\Registry\TraceableMessageHandlerRegistry'
            - '@logger'
        tags:
            - { name: console.command }

    Akeneo\Tool\Bundle\MessengerBundle\Command\TestCommand:
        arguments:
            - '@akeneo_messenger.bus.proxy'
        tags:
            - { name: console.command }
