queues:
    launch_product_evaluations_queue:
        env_var: PUBSUB_TOPIC_LAUNCH_PRODUCT_EVALUATIONS_QUEUE
        message_class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Messenger\LaunchProductAndProductModelEvaluationsMessage
        consumers:
            - name: dqi_launch_product_evaluations_consumer
              env_var: PUBSUB_SUBSCRIPTION_DQI_LAUNCH_PRODUCT_EVALUATIONS_CONSUMER
              service_handler: 'Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Messenger\LaunchProductAndProductModelEvaluationsHandler'

    created_or_updated_attribute_queue:
        env_var: PUBSUB_TOPIC_CREATED_OR_UPDATED_ATTRIBUTE_QUEUE
        message_class: Akeneo\Pim\Structure\Component\Event\AttributesWereCreatedOrUpdated
        consumers:
            - name: dqi_evaluate_attribute_consumer
              env_var: PUBSUB_SUBSCRIPTION_DQI_EVALUATE_ATTRIBUTE_CONSUMER
              service_handler: ''
