services:
    akeneo.pim.enrichment.command.calculate_product_completeness:
        class: 'Akeneo\Pim\Enrichment\Bundle\Command\CalculateCompletenessCommand'
        arguments:
            - '@akeneo.pim.enrichment.elasticsearch.indexer.product_and_ancestors'
            - '@pim_catalog.completeness.product.compute_and_persist'
            - '@database_connection'
        tags:
            - { name: 'console.command' }

    akeneo.pim.enrichment.command.index_product:
        class: 'Akeneo\Pim\Enrichment\Bundle\Command\IndexProductCommand'
        arguments:
            - '@akeneo.pim.enrichment.elasticsearch.indexer.product_and_ancestors'
            - '@akeneo_elasticsearch.client.product_and_product_model'
            - '@database_connection'
        tags:
            - { name: 'console.command' }

    akeneo.pim.enrichment.command.index_product_model:
        class: 'Akeneo\Pim\Enrichment\Bundle\Command\IndexProductModelCommand'
        arguments:
            - '@akeneo_elasticsearch.client.product_and_product_model'
            - '@pim_catalog.elasticsearch.indexer.product_model_descendants_and_ancestors'
            - '@database_connection'
        tags:
            - { name: 'console.command' }
    base_uuid_migration_step:
        arguments:
            - '@database_connection'
            - '@monolog.logger'
        abstract: true
    Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidCreateColumns:
        parent: base_uuid_migration_step

    Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidFillProductUuid:
        parent: base_uuid_migration_step

    Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidFillForeignUuid:
        parent: base_uuid_migration_step

    Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidFillJson:
        parent: base_uuid_migration_step

    Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidAddTriggers:
        parent: base_uuid_migration_step

    Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidCommand:
        arguments:
            - '@monolog.logger'
            - '@Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidCreateColumns'
            - '@Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidFillProductUuid'
            - '@Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidFillForeignUuid'
            - '@Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidFillJson'
            - '@Akeneo\Pim\Enrichment\Bundle\Command\MigrateToUuidAddTriggers'
        tags:
            - { name: 'console.command' }
