services:

  Akeneo\Platform\Installer\Application\DatabaseInstall\DatabaseInstallHandler:
    arguments:
      - '@Akeneo\Platform\Installer\Infrastructure\CommandExecutor\CreateTable'
      - '@Akeneo\Platform\Installer\Infrastructure\CommandExecutor\SetLatestMigration'
      - '@Akeneo\Platform\Installer\Infrastructure\Query\Sql\InsertDatabaseInstallationDate'
      - '@Akeneo\Platform\Installer\Infrastructure\Query\Elasticsearch\ResetIndexes'
      - '@doctrine.orm.default_entity_manager'
      - '@event_dispatcher'

  Akeneo\Platform\Installer\Application\FixturesLoad\FixturesLoadHandler:
    arguments:
      - '@Akeneo\Platform\Installer\Infrastructure\Query\Yaml\GetJobDefinition'
      - '@Akeneo\Platform\Installer\Infrastructure\Query\Sql\RemoveJobInstance'
      - '@Akeneo\Platform\Job\Application\CreateJobInstanceHandler'
      - '@Akeneo\Platform\Job\Application\LaunchJobInstance\LaunchJobInstanceHandler'
      - '@event_dispatcher'
      - [ 'AkeneoInstallerBundle/Resources/fixtures/fixtures_jobs.yml' ]
